-- Audiencias, fase 1: tablas, reglas y permisos (docs/plan-audiencias.md).
--
-- Ciclo: Programada → Realizada (desde 1 hora después y con grabación) o Cancelada (desde la hora
-- programada). Una audiencia cerrada solo admite corregir la grabación de una Realizada. Las reglas
-- viven en el trigger hearings_rules y se aplican a toda escritura con usuario (dashboard o API);
-- el SQL Editor y la service role (sin usuario) no las aplican, como en Avisos de Remate.
--
-- Permisos por juzgado: audiencias.ver|crear|editar|eliminar (juzgado, oficina, director_oficina)
-- y audiencias.tipos (catálogo de tipos; solo superadmin).

-- ---------------------------------------------------------------------------------------------
-- Catálogos fijos: juzgados de ejecución y estados.
-- ---------------------------------------------------------------------------------------------
create table if not exists public.execution_courts (
  id smallint primary key constraint execution_courts_id_chk check (id in (1, 2)),
  name text not null
);

insert into public.execution_courts (id, name) values
  (1, 'Juzgado 1 Civil del Circuito de Ejecución de Sentencias de Bucaramanga'),
  (2, 'Juzgado 2 Civil del Circuito de Ejecución de Sentencias de Bucaramanga')
on conflict (id) do update set name = excluded.name;

create table if not exists public.hearing_statuses (
  id smallint primary key,
  code text not null unique constraint hearing_statuses_code_chk check (code in ('programada', 'realizada', 'cancelada')),
  description text not null
);

insert into public.hearing_statuses (id, code, description) values
  (1, 'programada', 'Programada'),
  (2, 'realizada', 'Realizada'),
  (3, 'cancelada', 'Cancelada')
on conflict (id) do update set code = excluded.code, description = excluded.description;

alter table public.execution_courts enable row level security;
alter table public.hearing_statuses enable row level security;
revoke all on table public.execution_courts, public.hearing_statuses from anon, authenticated;
grant select on table public.execution_courts, public.hearing_statuses to anon, authenticated;

drop policy if exists execution_courts_select on public.execution_courts;
create policy execution_courts_select on public.execution_courts for select to anon, authenticated using (true);
drop policy if exists hearing_statuses_select on public.hearing_statuses;
create policy hearing_statuses_select on public.hearing_statuses for select to anon, authenticated using (true);

-- ---------------------------------------------------------------------------------------------
-- Tipos de audiencia (CRUD: audiencias.tipos).
-- ---------------------------------------------------------------------------------------------
create table if not exists public.hearing_types (
  id smallint generated by default as identity primary key,
  description text not null
    constraint hearing_types_description_chk check (char_length(trim(description)) between 3 and 80),
  requires_link boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists hearing_types_description_key on public.hearing_types (lower(trim(description)));

insert into public.hearing_types (description, requires_link)
select v.description, v.requires_link
from (values
  (1, 'Audiencia de Incidente', true),
  (2, 'Audiencia de Nulidad', true),
  (3, 'Audiencia de Oposición', true),
  (4, 'Audiencia de Remate', true),
  (5, 'Audiencia de Pruebas', true),
  (6, 'Comité de Entrega', true),
  (7, 'Diligencia de Secuestro', false),
  (8, 'Diligencia de Entrega', false)
) as v(n, description, requires_link)
where not exists (select 1 from public.hearing_types t where lower(t.description) = lower(v.description))
order by v.n;

alter table public.hearing_types enable row level security;
revoke all on table public.hearing_types from anon, authenticated;
grant select on table public.hearing_types to anon, authenticated;
grant insert (description, requires_link, is_active) on table public.hearing_types to authenticated;
grant update (description, requires_link, is_active) on table public.hearing_types to authenticated;
grant delete on table public.hearing_types to authenticated;

drop policy if exists hearing_types_select on public.hearing_types;
create policy hearing_types_select on public.hearing_types for select to anon, authenticated using (true);
drop policy if exists hearing_types_insert on public.hearing_types;
create policy hearing_types_insert on public.hearing_types
  for insert to authenticated with check ((select public.has_permission('audiencias.tipos')));
drop policy if exists hearing_types_update on public.hearing_types;
create policy hearing_types_update on public.hearing_types
  for update to authenticated
  using ((select public.has_permission('audiencias.tipos')))
  with check ((select public.has_permission('audiencias.tipos')));
drop policy if exists hearing_types_delete on public.hearing_types;
create policy hearing_types_delete on public.hearing_types
  for delete to authenticated using ((select public.has_permission('audiencias.tipos')));

-- ---------------------------------------------------------------------------------------------
-- Audiencias.
-- ---------------------------------------------------------------------------------------------
create table if not exists public.hearings (
  id uuid primary key default gen_random_uuid(),
  scheduled_at timestamptz not null,
  hearing_type_id smallint not null references public.hearing_types (id),
  case_number text not null constraint hearings_case_number_chk check (case_number ~ '^[0-9]{23}$'),
  court_id smallint not null references public.execution_courts (id),
  connection_url text constraint hearings_connection_url_chk check (connection_url ~ '^https://\S+$'),
  recording_url text constraint hearings_recording_url_chk check (recording_url ~ '^https://\S+$'),
  status_id smallint not null default 1 references public.hearing_statuses (id),
  notes text constraint hearings_notes_chk check (char_length(notes) <= 1000),
  created_by uuid default auth.uid() references auth.users (id) on delete set null,
  updated_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  -- Un radicado no tiene dos audiencias a la misma fecha y hora.
  constraint hearings_case_scheduled_key unique (case_number, scheduled_at)
);

create index if not exists hearings_scheduled_at_idx on public.hearings (scheduled_at);
create index if not exists hearings_court_scheduled_at_idx on public.hearings (court_id, scheduled_at);

-- Fecha y hora válidas para programar: futura, de lunes a viernes, día hábil, de 7:00 a. m. a
-- 5:00 p. m. (hora de Colombia) y en saltos de 15 minutos.
create or replace function public.hearing_schedule_error(p_scheduled_at timestamptz)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_local timestamp := p_scheduled_at at time zone 'America/Bogota';
begin
  if p_scheduled_at <= now() then
    return 'hearing_past';
  end if;
  if not public.is_business_day(v_local::date) then
    return 'hearing_non_business_day';
  end if;
  if v_local::time < time '07:00' or v_local::time > time '17:00' then
    return 'hearing_out_of_hours';
  end if;
  if extract(minute from v_local)::integer % 15 <> 0 or extract(second from v_local) <> 0 then
    return 'hearing_invalid_minutes';
  end if;
  return null;
end;
$$;

create or replace function public.hearings_rules()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_error text;
begin
  if tg_op = 'DELETE' then
    if v_user is not null
       and not (old.status_id = 1 and old.scheduled_at > now() and old.connection_url is null and old.recording_url is null) then
      raise exception 'hearing_not_deletable'
        using hint = 'Solo se elimina una audiencia programada, futura, sin enlace de conexión ni grabación.';
    end if;
    return old;
  end if;

  if tg_op = 'INSERT' then
    new.created_at := now();
    new.updated_at := null;
    new.updated_by := null;
    if v_user is null then
      return new;
    end if;
    new.created_by := v_user;
    new.status_id := 1;
    v_error := public.hearing_schedule_error(new.scheduled_at);
    if v_error is not null then
      raise exception '%', v_error;
    end if;
    if not exists (select 1 from public.hearing_types t where t.id = new.hearing_type_id and t.is_active) then
      raise exception 'hearing_type_inactive';
    end if;
    if new.recording_url is not null then
      raise exception 'hearing_recording_only_realizada';
    end if;
    return new;
  end if;

  -- UPDATE
  new.created_at := old.created_at;
  new.created_by := old.created_by;
  new.updated_at := now();
  new.updated_by := coalesce(v_user, old.updated_by);
  if v_user is null then
    return new;
  end if;

  -- Cerrada: solo se corrige la grabación de una Realizada.
  if old.status_id <> 1 then
    if (new.scheduled_at, new.hearing_type_id, new.case_number, new.court_id, new.connection_url, new.status_id, new.notes)
       is distinct from
       (old.scheduled_at, old.hearing_type_id, old.case_number, old.court_id, old.connection_url, old.status_id, old.notes)
       or (old.status_id <> 2 and new.recording_url is distinct from old.recording_url) then
      raise exception 'hearing_closed';
    end if;
    if old.status_id = 2 and new.recording_url is null then
      raise exception 'hearing_recording_required';
    end if;
    return new;
  end if;

  if new.status_id = 1 then
    if new.scheduled_at is distinct from old.scheduled_at then
      v_error := public.hearing_schedule_error(new.scheduled_at);
      if v_error is not null then
        raise exception '%', v_error;
      end if;
    end if;
    if new.hearing_type_id is distinct from old.hearing_type_id
       and not exists (select 1 from public.hearing_types t where t.id = new.hearing_type_id and t.is_active) then
      raise exception 'hearing_type_inactive';
    end if;
    if new.recording_url is not null then
      raise exception 'hearing_recording_only_realizada';
    end if;
    return new;
  end if;

  -- Cierre: la fecha y los datos del proceso no cambian al cerrar.
  if (new.scheduled_at, new.hearing_type_id, new.case_number, new.court_id)
     is distinct from (old.scheduled_at, old.hearing_type_id, old.case_number, old.court_id) then
    raise exception 'hearing_close_with_changes';
  end if;

  if new.status_id = 2 then
    if now() < old.scheduled_at + interval '1 hour' then
      raise exception 'hearing_too_early_to_close';
    end if;
    if new.recording_url is null then
      raise exception 'hearing_recording_required';
    end if;
  elsif new.status_id = 3 then
    if now() < old.scheduled_at then
      raise exception 'hearing_too_early_to_cancel';
    end if;
    if new.recording_url is not null then
      raise exception 'hearing_recording_only_realizada';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists hearings_rules on public.hearings;
create trigger hearings_rules
  before insert or update or delete on public.hearings
  for each row execute function public.hearings_rules();

revoke execute on function public.hearings_rules() from public, anon, authenticated;

alter table public.hearings enable row level security;
revoke all on table public.hearings from anon, authenticated;
grant select on table public.hearings to authenticated;
grant insert (scheduled_at, hearing_type_id, case_number, court_id, connection_url, notes)
  on table public.hearings to authenticated;
grant update (scheduled_at, hearing_type_id, case_number, court_id, connection_url, recording_url, status_id, notes)
  on table public.hearings to authenticated;
grant delete on table public.hearings to authenticated;

drop policy if exists hearings_select on public.hearings;
create policy hearings_select on public.hearings
  for select to authenticated using ((select public.has_permission('audiencias.ver', court_id)));
drop policy if exists hearings_insert on public.hearings;
create policy hearings_insert on public.hearings
  for insert to authenticated with check ((select public.has_permission('audiencias.crear', court_id)));
drop policy if exists hearings_update on public.hearings;
create policy hearings_update on public.hearings
  for update to authenticated
  using ((select public.has_permission('audiencias.editar', court_id)))
  with check ((select public.has_permission('audiencias.editar', court_id)));
drop policy if exists hearings_delete on public.hearings;
create policy hearings_delete on public.hearings
  for delete to authenticated using ((select public.has_permission('audiencias.eliminar', court_id)));

-- ---------------------------------------------------------------------------------------------
-- Funciones de apoyo del dashboard.
-- ---------------------------------------------------------------------------------------------

-- Días no hábiles de un rango para el calendario y el formulario. La tabla solo la lee quien tiene
-- calendario.ver; esto expone solo fecha y motivo a quien gestiona audiencias.
create or replace function public.hearing_non_business_days(p_from date, p_to date)
returns table (day date, reason text)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.has_permission('audiencias.ver') then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if p_to < p_from or p_to - p_from > 400 then
    raise exception 'invalid_period';
  end if;
  return query
    select n.day, n.reason from public.non_business_days n
    where n.day between p_from and p_to
    order by n.day;
end;
$$;

-- Quién creó y quién modificó por última vez (nombre o correo), para el detalle.
create or replace function public.hearing_audit(p_id uuid)
returns table (created_by_name text, updated_by_name text)
language sql
stable
security definer
set search_path = ''
as $$
  select
    coalesce(cp.full_name, cu.email::text),
    coalesce(up.full_name, uu.email::text)
  from public.hearings h
  left join public.profiles cp on cp.id = h.created_by
  left join auth.users cu on cu.id = h.created_by
  left join public.profiles up on up.id = h.updated_by
  left join auth.users uu on uu.id = h.updated_by
  where h.id = p_id
    and public.has_permission('audiencias.ver', h.court_id);
$$;

revoke execute on function public.hearing_schedule_error(timestamptz) from public, anon;
revoke execute on function public.hearing_non_business_days(date, date) from public, anon;
revoke execute on function public.hearing_audit(uuid) from public, anon;
grant execute on function public.hearing_schedule_error(timestamptz) to authenticated;
grant execute on function public.hearing_non_business_days(date, date) to authenticated;
grant execute on function public.hearing_audit(uuid) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- Permisos y asignación inicial.
-- ---------------------------------------------------------------------------------------------
insert into public.permissions (code, module, name, description) values
  ('audiencias.ver', 'audiencias', 'Ver audiencias', 'Ver las audiencias de su juzgado (o de los dos) en tabla y calendario.'),
  ('audiencias.crear', 'audiencias', 'Crear audiencias', 'Programar audiencias nuevas.'),
  ('audiencias.editar', 'audiencias', 'Editar audiencias', 'Editar audiencias programadas, marcarlas realizadas o canceladas y corregir la grabación.'),
  ('audiencias.eliminar', 'audiencias', 'Eliminar audiencias', 'Eliminar audiencias creadas por error (futuras, programadas, sin enlace ni grabación).'),
  ('audiencias.tipos', 'audiencias', 'Gestionar tipos de audiencia', 'Crear, editar, activar y eliminar los tipos de audiencia.')
on conflict (code) do nothing;

insert into public.role_permissions (role_id, permission_code)
select r.id, p.code
from public.roles r
cross join (values ('audiencias.ver'), ('audiencias.crear'), ('audiencias.editar'), ('audiencias.eliminar')) as p(code)
where r.code in ('juzgado', 'oficina', 'director_oficina')
on conflict do nothing;
